hexlet_django_blog/articles/urls.py
from django.urls import path
from hexlet_django_blog.articles.views import (IndexView,
                                               ArticleView,
                                               ArticleFormCreateView,
                                               ArticleFormEditView,
                                               ArticleFormDeleteView)


app_name = 'articles'

urlpatterns = [
    path('', IndexView.as_view(), name='articles'),
    path('<int:id>/', ArticleView.as_view(), name='article'),
    path('create/', ArticleFormCreateView.as_view(), name='articles_create'),
    path('<int:id>/edit/', ArticleFormEditView.as_view(), name='articles_update'),
    path('<int:id>/delete/', ArticleFormDeleteView.as_view(), name='articles_delete'),
]

hexlet_django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('articles/', include('hexlet_django_blog.articles.urls')),
    path('admin/', admin.site.urls),
]

hexlet_django_blog/article/models.py
from django.db import models

class Article(models.Model):
    name = models.CharField(max_length=200) # название статьи
    body = models.TextField() # тело статьи
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

hexlet_django_blog/articles/models.py
from django.db import models


class Article(models.Model):
    name = models.CharField(max_length=200) # название статьи
    body = models.TextField() # тело статьи
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

hexlet_django_blog/articles/forms.py
from django.forms import ModelForm
from .models import Article

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['name', 'body']

hexlet_django_blog/articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib import messages
from hexlet_django_blog.articles.forms import ArticleForm
from hexlet_django_blog.articles.models import Article


class IndexView(View):

    def get(self, request, *args, **kwargs):
        articles = Article.objects.all()[:15]
        return render(request, 'articles/index.html', context={
            'articles': articles,
        })


class ArticleView(View):

    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, id=kwargs['id'])
        return render(request, 'articles/article.html', context={
            'article': article,
        })


class ArticleFormCreateView(View):

    def get(self, request, *args, **kwargs):
        form = ArticleForm()
        return render(request, 'articles/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = ArticleForm(request.POST)
        if form.is_valid():  # Если данные корректные, то сохраняем данные формы
            form.save()
            messages.success(request, "Статья успешно создана", extra_tags='success')
            return redirect('articles:articles')
        messages.error(request, "Ошибка в форме", extra_tags='danger')
        return render(request, 'articles/create.html', {'form': form})


class ArticleFormEditView(View):

    def get(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        form = ArticleForm(instance=article)
        return render(request, 'articles/update.html',
                      {'form': form, 'article_id': article_id})

    def post(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            messages.success(request, "Статья успешно изменена", extra_tags='success')
            return redirect('articles:articles')
        messages.error(request, "Ошибка в форме", extra_tags='danger')
        return render(request, 'articles/update.html',
                      {'form': form, 'article_id': article_id})

class ArticleFormDeleteView(View):

    def post(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        if article:
            article.delete()
        messages.success(request, "Статья успешно удалена", extra_tags='success')
        return redirect('articles:articles')

views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')

templates/about.html
{% extends "base.html" %}

{% block title %}Эксперименты с Django на Хекслете{% endblock %}

{% block content %}
    <h1>О блоге</h1>
    <p>Эксперименты с Django на Хекслете</p>
    <p>{{ tags|join:', ' }}</p>
{% endblock %}

templates/article.html
{% extends "base.html" %}

{% block title %}Статья{% endblock %}

{% block content %}
    <h1>Статья номер {{article_id}}. Тег {{tags}}</h1>
{% endblock %}

templates/articles/article.html
{% extends "base.html" %}

{% block content %}
     <h1>{{ article.name }}</h1>
    <div>{{ article.body }}</div>
{% endblock %}

templates/articles/create.html
{% extends "base.html" %}

{% block content %}
{% if form.errors %}
<div>
    <ul>
    {% for error in form.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ul>
</div>
{% endif %}
<form action="{% url 'articles:articles_create' %}" method="post">
    {% csrf_token %}
    <table border="1">
    {{ form }}
    </table>
    <input type="submit" value="Создать">
</form>
{% endblock %}

templates/articles/index.html
{% extends "base.html" %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <h1>Список статей</h1>
<a href="{% url 'articles:articles_create' %}">Добавить статью</a>
    {% for article in articles %}
        <h2> <a href="{% url 'articles:article' article.id %}"> {{ article.name }}</a></h2>
        <div>{{ article.body|slice:":200" }}<p> <a href="{% url 'articles:articles_update' article.id %}"> Редактировать </a></p></div>
 <form action="{% url 'articles:articles_delete' article.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
</form>

    {% endfor %}
{% endblock %}

templates/articles/update.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% if form.errors %}
    <div>
        <ul>
        {% for error in form.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
        </ul>
    </div>
{% endif %}

<form action="{% url 'articles:articles_update' id=article_id %}" method="post">
    {% csrf_token %}
    <table border="1">
    {{ form }}
    </table>
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Django на Хекслете{% endblock %}</title>
</head>
<body>
<div id="sidebar">
    {% block sidebar %}
        <ul>
            <li><a href="/">Главная</a></li>
            <li><a href="/articles/">Статьи</a></li>
        </ul>
    {% endblock %}
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Мой Блог</h1>
{% endblock %}